### ISSUE TITLE
Fourth Tier JIT Backend

### ISSUE THREAD

**Issue by zNoctum** [luajit-remake/luajit-remake#18]
Seeing that you are making sizeable progress on the DFG JIT i wanted to ask if there are any concrete plans for the backend of the Fourth Tier JIT and if not if you would mind me implementing it. In the case there arent any plans and you wouldnt mind i think the best way for the backend is to write so its only representation type is based on the generated target specific assembly similarly to B3 Air just that it wont be generated from some higher level representation but just used directly. I think that is the smartest idea because the only alternative i have come up with is to have a B3 esque backend or just B3 and build a llvm backend that generates c++ that interface with this backend the big drawback i see with this is that it one requires too write a backend for llvm which isnt a small undertaking and because of the inherit instability of llvm ir would require repeated engineering work to just stay working (also there is the slight downside of having a not necessarily needed in between layer that adds compiletime i.e. the c like ir in B3).

Also using asm directly would allow us to keep working on it without having to fix #8 first.

**Comment by sillycross** [comment]
First, you should try to write readable sentences with **proper use of commas and periods** and proper separation of paragraphs. It helps communication and demonstrates your respect on the reader's time. 

You are correct that for the 4th tier we need a lower-level IR similar to B3. However, I don't see how you could avoid writing a LLVM IR to "our IR" transpiler, since the input bytecode semantics are all represented in LLVM IR (from the C++ code). 

I think the most straightforward approach is to reuse B3 as our low-level IR, and write a LLVM IR to B3 transpiler. There are a few issues that come to my mind:
1. B3 probably doesn't have a serialization format right now, so you need to invent one.
2. B3's data type is a subset of LLVM's data type, so probably you have to do something smart or have some sort of extension.

If you are willing to do that it would be greatly helpful. This is also independent of all the existing code, so it does not even need to sit in this repo.

**Comment by zNoctum** [comment]
When it comes to the serialization format i would, for now at least, just generate C++ files. And for (2) i would just build a LLVM backend that targets B3.

**Comment by sillycross** [comment]
I mean, the format where the B3 IR is represented is relatively minor. Emitting C++ file directly has advantages and disadvantages, but it's not the core part of the design. If you are seriously considering working on this, you probably want to think through and draft a plan first, of course I'm happy to take a look and give feedback if you are willing to do that.

**Comment by zNoctum** [comment]
So i have gotten llvm to emit B3 IR though i have only added add and return for now to the InstrInfo.td but extending it will be quite easy and due to how llvm is structured it seems that the best way forward is not to emit C++ directly but i have settled on something like
<code>add_i32(Int32 @1, Int32 @2) {
// %bb.1:
	Int32 @1 = Arg(0)
	Int32 @2 = Arg(1)
	Int32 @3 = Add(@1, @2)
	Void Return(@3)
}</code> though currently llvm still emits something like <code>add_i32(Int32 @1, Int32 @2) {
// %bb.1:
	Int32 @1 = Arg(0)
	Int32 @2 = Arg(1)
	Int32 @3 = Add(@1, @2)
	Void Return(@3)</code>
another thing i will need to work on is implementing pointers because of the definition of pointers B3 uses (namely a call to a function that may return Int32 or Int64). 

So to sum it all up progress is good and we should at some point have a chat how the B3 text IR -> B3 C++ file pipeline should work and how the interface of those C++ files should look like.

**Comment by sillycross** [comment]
> though i have only added add and return for now to the InstrInfo.td 

This sounds very interesting. If I understand it correctly, your approach is to add a new "B3 IR" backend inside LLVM, instead of having an external tool that converts LLVM IR to B3?

> So to sum it all up progress is good and we should at some point have a chat how the B3 text IR -> B3 C++ file pipeline should work and how the interface of those C++ files should look like.

I agree. I'm happy to schedule a time to chat on how thing should work. Feel free to send me an email at haoranxu510@gmail.com to set up the details.

**Comment by zNoctum** [comment]
> This sounds very interesting. If I understand it correctly, your approach is to add a new "B3 IR" backend inside LLVM, instead of having an external tool that converts LLVM IR to B3
Yes that is correct and since then I have also implemented Phi and Branch lowering aswell as a rudimentary implementation for memory operations.
> I agree. I'm happy to schedule a time to chat on how thing should work. Feel free to send me an email at [haoranxu510@gmail.com](mailto:haoranxu510@gmail.com) to set up the details.
Sent you one.

**Comment by sillycross** [comment]
A serious problem with implementing this inside the LLVM source tree is that it's difficult to keep up with new LLVM versions, since you need to deal with all the merge issues. Is there any reason that this has to be done inside LLVM instead of as external code that uses the LLVM library?

**Comment by zNoctum** [comment]
No you could also do this in a specialized tool but that would require replicating a lot of the legalizing and ISel infrastructure and regarding the stability of the LLVM code base this should be doable due too the backend interface being quite stable/having a long time to deprecate (for example SelectionDAG is still support even though GlobalISel was introduced 7 years ago to replace both it and FastISel) and me having only made about a dozent of small one line changes add the b3 triple to llvm that arent contained in the backend itself.

That why i think it is less work to occasionally adapt to the slight changes in backend infrastructure opposed to having to adapt to the ever changing IR of LLVM (for example there are plans to replace `getelementptr` with `ptradd` see [here](https://www.npopov.com/2024/01/01/This-year-in-LLVM-2023.html) which would require more work than having a LLVM backend because it already uses ptradd internally for the backend, also there weren't any major changes (i.e. new opcode only intrinsics) added to the [gMIR](https://github.com/llvm/llvm-project/commits/56d45b09dcd6c880215481bcc3c6d6281a04d264/llvm/include/llvm/CodeGen/ISDOpcodes.h))

**Comment by zNoctum** [comment]
Also it makes it easier to test if everything still works as expected because you could make use of LLVM's `lit` testing infrastructure (which was made to test exactly the kind of transforms this tool would be implementing).

**Comment by sillycross** [comment]
The explanation makes some sense, but I still have a few questions:
1. Why do you have to concern about ISel? I think B3 is at a similar abstraction level as LLVM IR? Can you give an example that ISel is useful here? (or, what exactly ISel are you referring to?)
2. Is there any possibility that you just emit somewhat naive B3 IR from LLVM IR, then run the B3 optimizer?

I guess my main question is that (as far as I understand) LLVM backend is mostly to leverage the target-specific properties (e.g., x64 instruction addressing modes), but my understanding is that B3 is not having any of these (in JSC they are done at Air level). So I don't quite get why you need any of the LLVM backend infra.

**Comment by zNoctum** [comment]
because for example B3 only has (i8 -> i32), (i16 -> i32), (i32 -> i64) sign extend but llvm also has for example i16 -> i64 so that would be lowered to two instructions and there are many such cases and i dont think there are any passes in b3 that would optimize
the generated ir from llvm in any significant way as long as a basic combiner pass is included.

(Also idk if you care about that but it has native vector scalarization and thus would make supporting the whole of llvm ir far easier)

**Comment by zNoctum** [comment]
Quick update on the backend: it's now able to compile most LLVM IR. Adding full LLVM IR support should be straightforward, except for a few things.

However, I hit a roadblock - B3 doesn't support multiple return values, which the baseline JIT uses.

Since I'm unsure if we'll need multiple return values in the end and adding them to B3 might need a lot of engineering effort, I'm planning to clean1 up the backend codebase first and then tackle #8 if that is alright with you.

**Comment by sillycross** [comment]
> it's now able to compile most LLVM IR instructions. Adding full LLVM IR support should be straightforward, except for a few things.

That's impressive! Thanks for all the work!

> However, I hit a roadblock - B3 doesn't support multiple return values, which the baseline JIT uses.

Do you mean the C runtime calls that returns multiple values? If I understood it correctly, the thing you said is that B3 does not implement the C calling convention completely -- it only supported the simplified model where one primitive (int/float) value is returned, is that what you are saying? 
I can think of two solutions:
(1) Add support to B3. My belief is that implementing all the dark corners in the C callconv would be very hard. However, in practice in the codebase we only use C functions that return two values in two different regs, so it would be sufficient to add support for that case only in B3 and lock down the rest. I'm not sure how hard it is. 
(2) As a temporary solution, at LLVM level, before calling into your backend, generate wrappers for those functions. For example, if the LLVM code calls `<i64, i64> f()`, you generate a wrapper function `f_wrapper(ptr result)` and make the bytecode semantic allocate the temp var `result` and call f_wrapper instead. This hurts perf but does not need B3 changes.

> Since I'm unsure if we'll need multiple return values in the end 

I'm not sure if I follow what you are saying. Can you explain?

**Comment by zNoctum** [comment]
> Do you mean the C runtime calls that returns multiple values? If I understood it correctly, the thing you said is that B3 does not implement the C calling convention completely -- it only supported the simplified model where one primitive (int/float) value is returned, is that what you are saying?

Yes.

> Add support to B3. My belief is that implementing all the dark corners in the C callconv would be very hard. However, in practice in the codebase we only use C functions that return two values in two different regs, so it would be sufficient to add support for that case only in B3 and lock down the rest. I'm not sure how hard it is.

I agree that implementing the full C callconv would probably be overkill, and regarding B3 the biggest blocker in implementing it as well as the tail calls is that i haven't extracted it into a separate repo, that works independently form JSC.

> As a temporary solution, at LLVM level, before calling into your backend, generate wrappers for those functions. For example, if the LLVM code calls <i64, i64> f(), you generate a wrapper function f_wrapper(ptr result) and make the bytecode semantic allocate the temp var result and call f_wrapper instead. This hurts perf but does not need B3 changes.

Not having them in B3 is not a real problem for emitting because i can just act like they exist in the text representation of B3 that the backend currently generates.

> I'm not sure if I follow what you are saying. Can you explain?

I am not sure if the type specialized functions for the 4th tier will need multiple returns that is what i meant.

**Comment by zNoctum** [comment]
I think another viable solution could be to use Cranelift as the backend instead of B3 because:
 - It supports multiple returns.
 - It is build to be used independently from Wasmtime.
though it would require the project to use rust as a additional language.
I would love to hear your thoughts on this @sillycross.
